#! /usr/bin/perl

use FindBin;
use lib "$FindBin::Bin";
use bot 'Rook';
use Data::Dumper;

my %status;
our $| = 1;
on join => sub {
	my $msg = shift;
	if ($status{id}) {
		$status{players}{$msg->{player}{id}} = $msg->{player};
	}
	else {
		cmd 'status';
	}
};

on status => sub {
	my $msg = shift;
	%status = %{ $msg };
	if ($status{state} eq 'Dealing' && $status{public}{dealer} eq $status{id}) {
		cmd 'deal';
	}
	else {
		print Dumper $msg;
	}
};

on dealing => sub {
	my $msg = shift;
	$status{state} = 'Dealing';
	if ($msg->{dealer} eq $status{id}) {
		cmd 'deal';
	}
};

on deal => sub {
	my $msg = shift;
	$status{private}{hand} = $msg->{hand};
};

play;
