#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use File::Slurp;
use lib "$FindBin::Bin/../lib";

BEGIN {
    my $secret_file = "$FindBin::Bin/../lib/Gamed/.secret";
    unless ( -r $secret_file && -s _ ) {
        my @chars = ( 33 .. 126 );
        my $str;
        for ( 1 .. 64 ) {
            $str .= chr( $chars[ rand @chars ] );
        }
        write_file( $secret_file, $str );
    }
    require Gamed;
    $Gamed::TEST = 1 if grep { /-test/ } @ARGV;
    $Gamed::DEV  = 1 if grep { /-dev/ } @ARGV;
}
use Gamed::Mojo;
