#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

BEGIN {
    if (@ARGV > 0 && $ARGV[0] eq '-test') {
        require Gamed;
        Gamed->import('Gamed::Test::Game');
    }
}
use Gamed::Mojo;
